config/routes.rb
SampleDatamapper::Application.routes.draw do
  resources :pictures do
    resources :comments
  end
  
  root :to => "pictures#index"

end

app/models/comment.rb
class Comment
  include Tire::Model::Search
  include DataMapper::Resource
  
  property :id, Serial
  property :title, String
  property :description, Text
  property :picture_id, Integer
  property :type, String, :default => "comment"
  
  belongs_to :picture, :touch => true  
  
  #Search in elasticsearch
  def self.search q
  
    begin
      result = tire.search do
        query {string ("picture_id:#{q}")}
      end
      return result.any? ? result : Comment.all(:picture_id => q)
    rescue Exception => e
      puts "Exception in search Comments: #{e.message}"
      Comment.all(:picture_id => q) #if any exception then return from database
    end
    
  end

  #Storing in elasticsearch
  def self.store_to_elasticsearch comment
    Tire.index "comments" do
      store comment.attributes
      refresh
    end
  end
  
end

app/models/picture.rb
class Picture

  include DataMapper::Resource
  include Paperclip::Resource
  
  property :id, Serial
  property :title, String
  property :description, Text
  
  has_attached_file :image, 
                    :styles => { :thumb => "100x100>" },
                    :default_url => "/images/:style/missing.png"
                    
  has n, :comments, :dependent => :destroy
end

app/controllers/application_controller.rb
require 'dm-rails/middleware/identity_map'
class ApplicationController < ActionController::Base
  use Rails::DataMapper::Middleware::IdentityMap
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :set_comment, only: [:show, :edit, :update, :destroy]

  def index
    @comments = Comment.search params[:picture_id]
  end

  def create
    @comment = Comment.new(params[:comment])
    respond_to do |format|
      if @comment.save
        Comment.store_to_elasticsearch @comment
        format.js
      else
        format.js { render :js => "alert('Problem in saving comment')"}
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.get(params[:id])
    end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_filter :set_picture, only: [:show, :edit, :update, :destroy]

  def index
    @pictures = Picture.all.page params[:page]
  end

  def show
    @comment = Comment.new(:picture_id => @picture.id)
  end

  def new
    @picture = Picture.new
  end

  def create
    @picture = Picture.new(params[:picture])

    respond_to do |format|
      if @picture.save
        format.html { redirect_to @picture, notice: 'Picture was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.get(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_form.html.erb
<%= form_for([@picture,@comment],:remote => true) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.hidden_field :picture_id,:value=> @comment.picture_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/create.js.erb
$("#comment_list").append("Title : <%= @comment.title %> | Description : <%= @comment.description %> <br>")
$("#new_comment")[0].reset()

app/views/comments/index.js.erb
$("#comment_list").html("")
<% @comments.each do |c| %>
  $("#comment_list").append("Title : <%= c.title %> | Description : <%= c.description %> <br>")
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SampleDatamapper</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "jquery" %>
  <%= javascript_include_tag "jquery_ujs" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pictures/_form.html.erb
<%= form_for(@picture) do |f| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% @picture.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pictures/index.html.erb
<h1>Listing pictures</h1>

<table border="1">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Image</th>
      <th></th>

      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @pictures.each do |picture| %>
      <tr>
        <td><%= picture.title %></td>
        <td><%= picture.description %></td>
        <td><img src="<%= picture.image.url(:thumb) %>"></td>
        <td><%= link_to 'Show', picture %></td>
        <td><%= link_to 'Destroy', picture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @pictures %>
<br>

<%= link_to 'New Picture', new_picture_path %>

app/views/pictures/new.html.erb
<h1>New picture</h1>

<%= render 'form' %>

<%= link_to 'Back', pictures_path %>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>
<h2>Picture Detail</h2>
<p>
  <strong>Title:</strong>
  <%= @picture.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @picture.description %>
</p>
<p>
  <strong>Image:</strong>
  <img src="<%= @picture.image.url(:thumb) %>">
</p>

<br>

<h2>Create comment</h2>

<%= render "comments/form" %>

<%= link_to 'Back to list of pictures', pictures_path %>

<h2> Comments </h2> 
<%= link_to "Show Comments", picture_comments_path(@picture), :remote => true%>
<div id="comment_list"></div>